# -*- coding: utf-8 -*-
"""alimenticio.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VdMUznYxf7ijF4igoonU1bh15J1cAcT
"""

usuarios = {
    "gerente": "senha123",
    "estoquista": "abc456",
    "caixa": "def789"
}

def fazer_login():
  """Realiza o login do usuário."""
  tentativas = 3
  while tentativas > 0:
    nome_usuario = input("Digite seu nome de usuário: ")
    senha = input("Digite sua senha: ")

    if nome_usuario in usuarios and usuarios[nome_usuario] == senha:
      print(f"Login bem-sucedido! Bem-vindo(a), {nome_usuario}.")
      return nome_usuario
    else:
      tentativas -= 1
      if tentativas > 0:
        print(f"Credenciais inválidas. Tentativas restantes: {tentativas}")
      else:
        print("Número máximo de tentativas atingido. Login falhou.")
        return None

def fazer_logout(usuario_logado):
  """Realiza o logout do usuário."""
  if usuario_logado:
    print(f"Logout do usuário {usuario_logado} realizado com sucesso.")
  else:
    print("Nenhum usuário logado.")

usuario_atual = None


usuario_atual = fazer_login()


if usuario_atual:

  print("Realizando atividades no sistema...")

  fazer_logout(usuario_atual)
else:
  print("Não foi possível acessar o sistema.")

estoque = [
    ["Maçã", 2.50],
    ["Banana", 1.80],
    ["Arroz (5kg)", 25.00],
    ["Feijão (1kg)", 8.00],
    ["Leite (1L)", 4.50]
]


carrinho = []

def exibir_estoque():
  """Exibe os produtos disponíveis no estoque."""
  print("\n--- Estoque Disponível ---")
  for i, produto in enumerate(estoque):
    print(f"{i+1}. {produto[0]} - R${produto[1]:.2f}")
  print("-------------------------")

def adicionar_ao_carrinho():
  """Adiciona um item ao carrinho."""
  exibir_estoque()
  try:
    escolha_produto = int(input("Digite o número do produto que deseja adicionar ao carrinho: "))
    if 1 <= escolha_produto <= len(estoque):
      indice_produto = escolha_produto - 1
      quantidade = int(input(f"Digite a quantidade de '{estoque[indice_produto][0]}' que deseja adicionar: "))
      if quantidade > 0:

        item_encontrado = False
        for item in carrinho:
          if item[0] == indice_produto:
            item[1] += quantidade
            item_encontrado = True
            break
        if not item_encontrado:
          carrinho.append([indice_produto, quantidade])
        print(f"{quantidade}x '{estoque[indice_produto][0]}' adicionado(s) ao carrinho.")
      else:
        print("A quantidade deve ser maior que zero.")
    else:
      print("Número de produto inválido.")
  except ValueError:
    print("Entrada inválida. Por favor, digite um número.")

def exibir_carrinho():
  """Exibe os itens no carrinho."""
  print("\n--- Seu Carrinho ---")
  if not carrinho:
    print("Carrinho vazio.")
  else:
    total = 0
    for item in carrinho:
      indice_produto = item[0]
      quantidade = item[1]
      nome_produto = estoque[indice_produto][0]
      preco_unitario = estoque[indice_produto][1]
      subtotal = quantidade * preco_unitario
      print(f"- {quantidade}x {nome_produto} - R${subtotal:.2f}")
      total += subtotal
    print("---------------------")
    print(f"Total: R${total:.2f}")
  print("--------------------")

def remover_do_carrinho():
  """Remove um item do carrinho."""
  exibir_carrinho()
  if carrinho:
    try:
      escolha_remover = int(input("Digite o número do item no carrinho que deseja remover (ou 0 para cancelar): "))
      if 1 <= escolha_remover <= len(carrinho):
        del carrinho[escolha_remover - 1]
        print("Item removido do carrinho.")
      elif escolha_remover == 0:
        print("Remoção cancelada.")
      else:
        print("Número de item inválido.")
    except ValueError:
      print("Entrada inválida. Por favor, digite um número.")


if usuario_atual == "caixa":
  while True:
    print("\nOpções do Caixa:")
    print("1. Adicionar produto ao carrinho")
    print("2. Exibir carrinho")
    print("3. Remover item do carrinho")
    print("4. Finalizar compra")
    print("5. Sair")

    opcao = input("Escolha uma opção: ")

    if opcao == '1':
      adicionar_ao_carrinho()
    elif opcao == '2':
      exibir_carrinho()
    elif opcao == '3':
      remover_do_carrinho()
    elif opcao == '4':
      exibir_carrinho()
      print("\nCompra finalizada! Obrigado(a).")
      carrinho = []
      break
    elif opcao == '5':
      print("Saindo do sistema de caixa.")
      break
    else:
      print("Opção inválida. Tente novamente.")

elif usuario_atual:
    print("Este usuário não tem permissão para operar o caixa.")