# -*- coding: utf-8 -*-
"""GerenciamentoDePagamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZph-zwsXkWifg2Fqkr4bKQ1ns-eCz4e
"""

pagamentos = ['Pix', 'Cartão de débito', 'Cartão de crédito']

for i in range(len(pagamentos)):
  print(f'{i+1} - {pagamentos[i]}')

escolha = int(input('Qual forma de pagamento deseja? Pix, Cartão de débito ou Cartão de crédito'))

PagamentoSelecionado = pagamentos[escolha-1]

print(PagamentoSelecionado)

if escolha == 3 :
  NdeParcelas = input('Quantas parcelas deseja? Máximo 5')
  print(f'voce parcelou em {NdeParcelas}, sua compra foi realizada com sucesso')
else:
  print("Compra realizada com sucesso")