# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125nlb3r98NqVzyrsfWuqLGooFxwfxhiI
"""

Produtos = [
    [{"id": 1, "nomeProduto": "Maçã", "preco": 3.50, "Qtde": 200}],
    [{"id": 2, "nomeProduto": "Banana", "preco": 2.80, "Qtde": 300}],
    [{"id": 3, "nomeProduto": "Arroz", "preco": 12.90, "Qtde": 400}],
    [{"id": 4, "nomeProduto": "Feijão", "preco": 8.75, "Qtde": 100}],
    [{"id": 5, "nomeProduto": "Batata", "preco": 4.20, "Qtde": 200}],
    [{"id": 6, "nomeProduto": "Leite", "preco": 5.99, "Qtde": 600}],
    [{"id": 7, "nomeProduto": "Manteiga", "preco": 7.40, "Qtde": 90}],
    [{"id": 8, "nomeProduto": "Beterraba", "preco": 3.25, "Qtde": 80}],
    [{"id": 9, "nomeProduto": "Macarrão", "preco": 3.99, "Qtde": 100}]
]


print(f"\n{'Id':<3} | {'Nome':<12} | {'Preço':>8} | {'Qtde':>7}")
print("-"*40)


for produto in Produtos:
    print(f"{produto[0]['id']:<3} | {produto[0]['nomeProduto']:<12} | R$ {produto[0]['preco']:>5.2f} | {produto[0]['Qtde']:>7.0f}")


print("-"*40)
media = 0
QuantidadeTotal = 0
for i in Produtos:
    media += i[0]['preco']

for i in Produtos:
    QuantidadeTotal += i[0]['Qtde']
media /= len(Produtos)

print(f"Quantidade de Produtos: {QuantidadeTotal}")
print(f"{media:.2f}")

