# -*- coding: utf-8 -*-
"""login and logout

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VdMUznYxf7ijF4igoonU1bh15J1cAcT
"""

usuarios_cadastrados = ["caio", "marlon", "miguel", "pedro"]
senhas_cadastradas = ["senha123", "senha321", "senha789", "senha987"]
1
usuario = input("digite seu usuario: ")
senha = input("digite sua senha: ")


for i in range(len(usuarios_cadastrados)):
    if usuario == usuarios_cadastrados[i] and senha == senhas_cadastradas[i]:
        print("acesso permitido")
        break
else:
    print("acesso negado")