# -*- coding: utf-8 -*-
"""login and logout

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VdMUznYxf7ijF4igoonU1bh15J1cAcT
"""

usuarios_cadastrados = []
senhas_cadastradas = []
id_cadastrado = []
email_cadastrado = []
funcao_cadastrada = []

cadastrar_usuario = input("deseja cadastrar um usuario? (s/n): ")
if cadastrar_usuario == "s":
  novo_usuario = input("digite o novo usuario: ")
  nova_senha = input("digite a nova senha: ")
  novo_id = int(input("digite o novo id: "))
  novo_email = input("digite o novo email: ")
  nova_funcao = input("digite a nova funcao: ")
  usuarios_cadastrados.append(novo_usuario)
  senhas_cadastradas.append(nova_senha)
  id_cadastrado.append(novo_id)
  email_cadastrado.append(novo_email)
  funcao_cadastrada.append(nova_funcao)

else:
    print("ok")

id = int(input("digite seu id: "))
senha = input("digite sua senha: ")


for i in range(len(usuarios_cadastrados)):
    if id == id_cadastrado[i] and senha == senhas_cadastradas[i]:
        print("acesso permitido")
        break
else:
    print("acesso negado")


print("\n🔐 Dados do Usuário Logado:")
print(f"ID: {id_cadastrado[i]}")
print(f"Usuário: {usuarios_cadastrados[i]}")
print(f"Email: {email_cadastrado[i]}")
print(f"Função: {funcao_cadastrada[i]}")