# -*- coding: utf-8 -*-
"""MainAlimenticio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8TP-91f8eVZHiRidniqj9ceoGTPfCCq
"""

# -*- coding: utf-8 -*-
"""login and logout

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VdMUznYxf7ijF4igoonU1bh15J1cAcT
"""

usuarios_cadastrados = []
senhas_cadastradas = []
id_cadastrado = []
email_cadastrado = []
funcao_cadastrada = []

cadastrar_usuario = input("deseja cadastrar um usuario? (s/n): ")
if cadastrar_usuario == "s":
  novo_usuario = input("digite o novo usuario: ")
  nova_senha = input("digite a nova senha: ")
  novo_id = int(input("digite o novo id: "))
  novo_email = input("digite o novo email: ")
  nova_funcao = input("digite a nova funcao: ")
  usuarios_cadastrados.append(novo_usuario)
  senhas_cadastradas.append(nova_senha)
  id_cadastrado.append(novo_id)
  email_cadastrado.append(novo_email)
  funcao_cadastrada.append(nova_funcao)

else:
    print("ok")

id = int(input("digite seu id: "))
senha = input("digite sua senha: ")


for i in range(len(usuarios_cadastrados)):
    if id == id_cadastrado[i] and senha == senhas_cadastradas[i]:
        print("acesso permitido")
        break
else:
    print("acesso negado")


print("\n🔐 Dados do Usuário Logado:")
print(f"ID: {id_cadastrado[i]}")
print(f"Usuário: {usuarios_cadastrados[i]}")
print(f"Email: {email_cadastrado[i]}")
print(f"Função: {funcao_cadastrada[i]}")

# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125nlb3r98NqVzyrsfWuqLGooFxwfxhiI
"""

Produtos = [
    [{"id": 1, "nomeProduto": "Maçã", "preco": 3.50, "Qtde": 200}],
    [{"id": 2, "nomeProduto": "Banana", "preco": 2.80, "Qtde": 300}],
    [{"id": 3, "nomeProduto": "Arroz", "preco": 12.90, "Qtde": 400}],
    [{"id": 4, "nomeProduto": "Feijão", "preco": 8.75, "Qtde": 100}],
    [{"id": 5, "nomeProduto": "Batata", "preco": 4.20, "Qtde": 200}],
    [{"id": 6, "nomeProduto": "Leite", "preco": 5.99, "Qtde": 600}],
    [{"id": 7, "nomeProduto": "Manteiga", "preco": 7.40, "Qtde": 90}],
    [{"id": 8, "nomeProduto": "Beterraba", "preco": 3.25, "Qtde": 80}],
    [{"id": 9, "nomeProduto": "Macarrão", "preco": 3.99, "Qtde": 100}]
]


print(f"\n{'Id':<3} | {'Nome':<12} | {'Preço':>8} | {'Qtde':>7}")
print("-"*40)


for produto in Produtos:
    print(f"{produto[0]['id']:<3} | {produto[0]['nomeProduto']:<12} | R$ {produto[0]['preco']:>5.2f} | {produto[0]['Qtde']:>7.0f}")


print("-"*40)
media = 0
QuantidadeTotal = 0
for i in Produtos:
    media += i[0]['preco']

for i in Produtos:
    QuantidadeTotal += i[0]['Qtde']
media /= len(Produtos)

print(f"Quantidade de Produtos: {QuantidadeTotal}")
print(f"{media:.2f}")

# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125nlb3r98NqVzyrsfWuqLGooFxwfxhiI
"""

carrinho = []

while True:
    try:
        compra = int(input("Digite o código do produto que deseja colocar no carrinho [0 para finalizar]: "))
        if compra == 0:
            break

        produto_encontrado = None
        for produto in Produtos:
            if produto[0]['id'] == compra:
                produto_encontrado = produto
                break

        if produto_encontrado:
            carrinho.append(produto_encontrado)
            print(f"{produto_encontrado[0]['nomeProduto']} adicionado ao carrinho!")
        else:
            print("Produto não encontrado. Tente novamente.")

    except ValueError:
        print("Por favor, digite um número válido.")

if carrinho:
    print("\n{:-^40}".format(" SEU CARRINHO "))
    print(f"{'Produto':<20} | {'Preço':>10}")
    print("-" * 40)

    total = 0
    for item in carrinho:
        print(f"{item[0]['nomeProduto']:<20} | R$ {item[0]['preco']:>7.2f}")
        total += item[0]['preco']

    print("-" * 40)
    print(f"{'TOTAL:':<20} | R$ {total:>7.2f}")
    print("-" * 40)

    # -*- coding: utf-8 -*-
    """GerenciamentoDePagamento.ipynb

    Automatically generated by Colab.

    Original file is located at
        https://colab.research.google.com/drive/1fZph-zwsXkWifg2Fqkr4bKQ1ns-eCz4e
    """

    pagamentos = ['Pix', 'Cartão de débito', 'Cartão de crédito']

    for i in range(len(pagamentos)):
      print(f'{i+1} - {pagamentos[i]}')

    escolha = int(input('Qual forma de pagamento deseja? Pix, Cartão de débito ou Cartão de crédito'))

    PagamentoSelecionado = pagamentos[escolha-1]

    print(PagamentoSelecionado)

    if escolha == 3 :
      NdeParcelas = input('Quantas parcelas deseja? Máximo 5')
      print(f'voce parcelou em {NdeParcelas}, sua compra foi realizada com sucesso')
    else:
      print("Compra realizada com sucesso")
else:
    print("Nenhum item no carrinho")