# -*- coding: utf-8 -*-
"""sistema de carrinho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEI-Vq3-i7dzPuPaAVSCaS38hDZ-yi2Y
"""

